# Synthelion — Python port of Caveman (https://github.com/francescopaolopassaro/caveman)
# © 2026 Passaro Francesco Paolo — Digitalsolutions.it
"""Compliance document generation.

Four documents, each built from the *live* configuration and the real audit
trail rather than from a hand-maintained template:

  technical_file  — EU AI Act Art. 11 / Annex IV system file
  dpia            — GDPR Art. 35 data protection impact assessment
  fria            — EU AI Act Art. 27 fundamental rights impact assessment
  executive_report— periodic operational compliance report

Every document is available as a dict (JSON) and as a PDF. The dict is the
source of truth; the PDF renders it. That ordering matters: a regulator or an
internal system can consume the JSON, and nothing in the report exists only as
pixels.

These are **pre-filled working drafts, not finished legal instruments.** A
DPIA and a FRIA both require judgements — necessity, proportionality, residual
risk acceptance — that no engine can make on an organisation's behalf. What
this module supplies is every fact the assessment needs: which controls run,
which data categories were actually observed, what was blocked, and where
obligations are left uncovered. The sections requiring human judgement are
emitted explicitly as open items rather than filled with plausible text.
"""
from __future__ import annotations

import time
from pathlib import Path

from synthelion.compliance import audit
from synthelion.compliance.engine import ComplianceEngine
from synthelion.compliance.pdf import PdfDocument
from synthelion.compliance.rules import coverage_gaps, traceability_matrix

_DISCLAIMER = (
    "Generated by the Synthelion Compliance Engine from the live configuration and audit "
    "trail. It is a technical working draft: sections requiring an organisational judgement "
    "are listed as open items and must be completed and approved by the controller, the DPO "
    "or the appointed assessor before the document is relied upon."
)


def _now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())


def _engine_snapshot(engine: ComplianceEngine) -> dict:
    return {
        "status": engine.status,
        "fallback": engine.fallback,
        "language": engine.language,
        "agent_profile": engine.agent_profile,
        "system_prompt_override": bool(engine.system_prompt_override),
        "rules": [r.to_dict() for r in engine.rules],
        "rules_enabled": sum(1 for r in engine.rules if r.enabled),
        "rules_total": len(engine.rules),
    }


# ---------------------------------------------------------------------------
# Documents (dict form)
# ---------------------------------------------------------------------------

def technical_file(engine: ComplianceEngine | None = None, directory=None) -> dict:
    """EU AI Act Art. 11 / Annex IV technical documentation."""
    engine = engine or ComplianceEngine.from_config()
    import synthelion

    chain = audit.verify_chain(directory=directory)
    return {
        "document": "Technical Documentation (EU AI Act Art. 11, Annex IV)",
        "generated_at": _now(),
        "disclaimer": _DISCLAIMER,
        "system": {
            "name": "Synthelion AI Compliance Engine",
            "version": getattr(synthelion, "__version__", "unknown"),
            "role": "Security and governance gateway between client applications and "
                    "third-party generative AI models.",
            "deployment": "Self-hosted. Prompts and responses are processed locally; no "
                          "telemetry is emitted to the vendor.",
        },
        "engine": _engine_snapshot(engine),
        "guardrails": [r.to_dict() for r in engine.rules],
        "traceability_matrix": traceability_matrix(engine.rules),
        "coverage_gaps": coverage_gaps(engine.rules),
        # A control switched on whose guard is switched off elsewhere is the
        # one thing a technical file must never quietly omit.
        "backend_health": engine.backend_health(),
        "ineffective_controls": engine.ineffective_rules(),
        "record_keeping": {
            "mechanism": "Hash-chained append-only JSONL audit trail (Art. 12).",
            "entries": chain.entries,
            "chain_valid": chain.valid,
            "chain_note": chain.reason or "No tampering detected.",
            "content_policy": "Only a SHA-256 fingerprint of each payload is stored, never the "
                              "prompt or response text.",
        },
        "human_oversight": {
            "article": "EU AI Act Art. 14",
            "mechanisms": [
                "Gated actions: operations classified as requiring approval are refused by the "
                "policy engine until an operator authorises them out of band.",
                "Engine status can be set to inactive or staging at any time, taking the gateway "
                "out of enforcement without a redeploy.",
                "Every decision is reviewable in the audit trail and the live monitor.",
            ],
        },
        "open_items": [
            "Assign the intended purpose and the risk classification of each connected use case "
            "(Art. 6 and Annex III).",
            "Record the accuracy metrics and operational limits communicated to users (Art. 13).",
            "Attach the provider documentation of each connected third-party model (Art. 53).",
        ],
    }


def dpia(engine: ComplianceEngine | None = None, since: float | None = None, directory=None) -> dict:
    """GDPR Art. 35 data protection impact assessment."""
    engine = engine or ComplianceEngine.from_config()
    stats = audit.statistics(since=since, directory=directory)
    privacy_rules = [r for r in engine.rules if r.category.value == "privacy"]
    observed = {k: v for k, v in stats["by_category"].items() if k == "privacy"}

    return {
        "document": "Data Protection Impact Assessment (GDPR Art. 35)",
        "generated_at": _now(),
        "disclaimer": _DISCLAIMER,
        "processing_description": {
            "purpose": "Filtering and governance of prompts and responses exchanged with "
                       "third-party generative AI models.",
            "nature": "Automated inspection in transit. Payload text is inspected in memory and "
                      "is not persisted by the engine.",
            "data_categories_observed": sorted(
                {c for rid, _ in stats["by_rule"].items() for c in [rid]}),
            "findings_in_period": observed,
        },
        "measures": {
            "minimisation": [r.to_dict() for r in privacy_rules],
            "storage": "The audit trail stores a SHA-256 fingerprint of each payload, never the "
                       "text — the log cannot itself become a source of personal data.",
            "transfers": "Personal data detected by the engine is redacted before the payload "
                         "reaches a third-party model endpoint.",
        },
        "necessity_and_proportionality": {
            "status": "requires human assessment",
            "note": "Whether the processing is necessary and proportionate to its purpose is a "
                    "controller judgement and is deliberately not auto-filled.",
        },
        "risks": {
            "identified": [
                "Residual personal data in free text not matched by any detector.",
                "Re-identification from combinations of individually non-identifying fields.",
                "Onward processing by the third-party model provider under its own terms.",
            ],
            "mitigations": [
                f"{len(privacy_rules)} privacy control(s) configured; "
                f"{sum(1 for r in privacy_rules if r.enabled)} currently enabled.",
                "Detection is confirmed by checksum and context keyword before masking, limiting "
                "both false positives and silent misses.",
            ],
            "residual_risk_acceptance": "requires human assessment",
        },
        "statistics": stats,
        "open_items": [
            "Record the lawful basis for the processing (Art. 6).",
            "Record the retention period applied to the audit trail.",
            "Record the outcome of the consultation with the DPO (Art. 35(2)).",
        ],
    }


def fria(engine: ComplianceEngine | None = None, since: float | None = None, directory=None) -> dict:
    """EU AI Act Art. 27 fundamental rights impact assessment."""
    engine = engine or ComplianceEngine.from_config()
    stats = audit.statistics(since=since, directory=directory)
    return {
        "document": "Fundamental Rights Impact Assessment (EU AI Act Art. 27)",
        "generated_at": _now(),
        "disclaimer": _DISCLAIMER,
        "deployment_context": {
            "description": "Gateway mediating employee and application access to generative AI "
                           "models.",
            "affected_persons": "requires human assessment",
            "frequency_and_duration": f"{stats['total_calls']} transaction(s) recorded in the "
                                      f"reporting period.",
        },
        "rights_assessment": [
            {
                "right": "Protection of personal data (Charter Art. 8)",
                "impact": "Mitigated by automated redaction before third-party transmission.",
                "controls": [r.id for r in engine.rules if r.category.value == "privacy" and r.enabled],
            },
            {
                "right": "Non-discrimination (Charter Art. 21)",
                "impact": "Model output may reflect bias present in the underlying model.",
                "controls": [r.id for r in engine.rules if r.category.value in ("safety", "content") and r.enabled],
                "note": "The engine screens output but does not evaluate the model for bias; that "
                        "assessment belongs to the model provider's documentation.",
            },
            {
                "right": "Human dignity and freedom of expression",
                "impact": "Content screening can over-block legitimate expression.",
                "controls": ["Engine staging mode allows a policy to be measured before it enforces."],
            },
            {
                "right": "Right to an effective remedy",
                "impact": "Affected persons must be able to contest an automated refusal.",
                "controls": ["Every decision is recorded with its rule id and risk level, making "
                             "a refusal explainable after the fact."],
                "note": "requires human assessment — the complaint channel is organisational.",
            },
        ],
        "oversight_measures": technical_file(engine, directory=directory)["human_oversight"]["mechanisms"],
        "statistics": stats,
        "open_items": [
            "Identify the categories of persons affected in this deployment.",
            "Define the complaint and redress channel offered to them.",
            "Notify the market surveillance authority where Art. 27(3) applies.",
        ],
    }


def executive_report(engine: ComplianceEngine | None = None, days: int = 30, directory=None) -> dict:
    """Periodic operational compliance report."""
    engine = engine or ComplianceEngine.from_config()
    since = time.time() - days * 86400
    stats = audit.statistics(since=since, directory=directory)
    chain = audit.verify_chain(directory=directory)
    return {
        "document": f"Executive Compliance Report — last {days} day(s)",
        "generated_at": _now(),
        "period_days": days,
        "engine": {"status": engine.status, "fallback": engine.fallback,
                   "rules_enabled": sum(1 for r in engine.rules if r.enabled),
                   "rules_total": len(engine.rules)},
        "statistics": stats,
        "audit_chain": chain.to_dict(),
        "coverage_gaps": coverage_gaps(engine.rules),
    }


# ---------------------------------------------------------------------------
# PDF rendering
# ---------------------------------------------------------------------------

def _render_open_items(doc: PdfDocument, items: list[str]) -> None:
    if not items:
        return
    doc.heading("Open items requiring human completion", size=12)
    for item in items:
        doc.paragraph(f"-  {item}", indent=6)


def _render_rules_table(doc: PdfDocument, rules: list[dict]) -> None:
    doc.table(
        ["Rule", "Category", "Risk", "Action", "Scope", "On"],
        [[r["id"], r["category"], r["risk_level"], r["action"], r["scope"],
          "yes" if r["enabled"] else "NO"] for r in rules],
        [0.30, 0.16, 0.12, 0.14, 0.14, 0.14],
    )


def _render_matrix(doc: PdfDocument, rows: list[dict]) -> None:
    doc.table(
        ["Module", "Framework", "Article", "Obligation"],
        [[r["module"], r["framework"], r["article"], r["obligation"]] for r in rows],
        [0.22, 0.20, 0.13, 0.45],
    )


def to_pdf(document: dict, path: "str | Path") -> Path:
    """Render any of the four documents to PDF."""
    doc = PdfDocument(
        title=document.get("document", "Compliance Document"),
        subtitle=f"Generated {document.get('generated_at', '')}",
        footer="Synthelion Compliance Engine",
    )

    if document.get("disclaimer"):
        doc.paragraph(document["disclaimer"], size=8.5, gray=0.4)
        doc.rule()

    if "system" in document:
        doc.heading("1. System", size=13)
        doc.key_values([(k.replace("_", " ").title(), str(v)) for k, v in document["system"].items()])

    if "engine" in document:
        engine = document["engine"]
        doc.heading("2. Engine configuration", size=13)
        doc.key_values([
            ("Status", str(engine.get("status"))),
            ("Fallback", str(engine.get("fallback"))),
            ("Agent profile", str(engine.get("agent_profile"))),
            ("Rules enabled", f"{engine.get('rules_enabled')} of {engine.get('rules_total')}"),
        ])

    if document.get("guardrails"):
        doc.heading("3. Active guardrails", size=13)
        _render_rules_table(doc, document["guardrails"])

    if document.get("traceability_matrix"):
        doc.heading("4. Traceability: control to legal obligation", size=13)
        _render_matrix(doc, document["traceability_matrix"])

    if "record_keeping" in document:
        doc.heading("5. Record keeping (Art. 12)", size=13)
        doc.key_values([(k.replace("_", " ").title(), str(v))
                        for k, v in document["record_keeping"].items()])

    if "human_oversight" in document:
        doc.heading("6. Human oversight (Art. 14)", size=13)
        for m in document["human_oversight"]["mechanisms"]:
            doc.paragraph(f"-  {m}", indent=6)

    # DPIA / FRIA specific sections
    for key, title in (("processing_description", "Processing description"),
                       ("measures", "Technical and organisational measures"),
                       ("necessity_and_proportionality", "Necessity and proportionality"),
                       ("deployment_context", "Deployment context")):
        if key in document:
            doc.heading(title, size=13)
            doc.key_values([(k.replace("_", " ").title(), str(v))
                            for k, v in document[key].items()])

    if "risks" in document:
        doc.heading("Risks", size=13)
        for risk in document["risks"].get("identified", []):
            doc.paragraph(f"-  {risk}", indent=6)
        doc.paragraph("Mitigations:", size=9.5)
        for m in document["risks"].get("mitigations", []):
            doc.paragraph(f"-  {m}", indent=6)
        doc.key_values([("Residual risk", str(document["risks"].get("residual_risk_acceptance", "")))])

    if "rights_assessment" in document:
        doc.heading("Fundamental rights assessment", size=13)
        doc.table(
            ["Right", "Impact", "Controls"],
            [[r["right"], r["impact"], ", ".join(r.get("controls", [])) or "—"]
             for r in document["rights_assessment"]],
            [0.26, 0.44, 0.30],
        )

    stats = document.get("statistics")
    if stats:
        doc.heading("Operational statistics", size=13)
        doc.key_values([
            ("Transactions processed", f"{stats['total_calls']:,}"),
            ("With findings", f"{stats['calls_with_findings']:,}"),
            ("Violation rate", f"{stats['violation_rate_pct']}%"),
            ("Latency added (avg / p95 / max)",
             f"{stats['latency_ms']['avg']} / {stats['latency_ms']['p95']} / "
             f"{stats['latency_ms']['max']} ms"),
        ])
        if stats.get("by_category"):
            doc.heading("Findings by category", size=11)
            doc.bar_chart(sorted(stats["by_category"].items(), key=lambda kv: -kv[1]))
        if stats.get("by_risk_level"):
            doc.heading("Findings by risk level", size=11)
            doc.bar_chart(sorted(stats["by_risk_level"].items(), key=lambda kv: -kv[1]))

    if "audit_chain" in document:
        chain = document["audit_chain"]
        doc.heading("Audit trail integrity", size=13)
        doc.key_values([
            ("Entries", str(chain.get("entries"))),
            ("Chain valid", "yes" if chain.get("valid") else "NO — see note"),
            ("Note", chain.get("reason") or "No tampering detected."),
        ])

    ineffective = document.get("ineffective_controls")
    if ineffective:
        doc.heading("Controls enabled but not operational", size=13)
        doc.paragraph("These rules are switched on in the compliance policy, but the guard that "
                      "implements them is disabled or unavailable — they currently inspect "
                      "nothing.", size=9, gray=0.35)
        doc.table(
            ["Rule", "Backend", "State", "Reason"],
            [[h["rule_id"], h["backend"], h["backend_state"], h["note"]] for h in ineffective],
            [0.26, 0.22, 0.16, 0.36],
        )

    gaps = document.get("coverage_gaps")
    if gaps:
        doc.heading("Uncovered obligations (disabled controls)", size=13)
        doc.paragraph("These obligations have no active control in the current configuration.",
                      size=9, gray=0.35)
        _render_matrix(doc, gaps)

    _render_open_items(doc, document.get("open_items", []))
    return doc.save(path)


GENERATORS = {
    "technical-file": technical_file,
    "dpia": dpia,
    "fria": fria,
    "executive-report": executive_report,
}


def generate(kind: str, **kwargs) -> dict:
    if kind not in GENERATORS:
        raise ValueError(f"unknown document {kind!r}; choose from {', '.join(sorted(GENERATORS))}")
    return GENERATORS[kind](**kwargs)
