# Synthelion — Python port of Caveman (https://github.com/francescopaolopassaro/caveman)
# © 2026 Passaro Francesco Paolo — Digitalsolutions.it
"""Node-to-node cluster join/heartbeat client.

Shared by the CLI (`synthelion cluster join`) and the dashboard's Cluster page
("Join a master" form) so there is exactly one implementation of "how a node
introduces itself to a master", instead of two that can drift apart.

Every call carries the cluster's shared secret as `Authorization: Bearer
<token>` — see dashboard.py's `_cluster_authenticated()` for the server side.
This is a separate auth scheme from the browser session cookie: node-to-node
calls have no browser and no login form.
"""
from __future__ import annotations

import json
import urllib.error
import urllib.request


class ClusterJoinError(Exception):
    pass


def _post(url: str, token: str, payload: dict, timeout: float = 8.0) -> dict:
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url, data=body, method="POST",
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {token}"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="ignore")
        raise ClusterJoinError(f"master rejected the request ({exc.code}): {detail}") from exc
    except urllib.error.URLError as exc:
        raise ClusterJoinError(f"could not reach master at {url}: {exc.reason}") from exc
    except json.JSONDecodeError as exc:
        raise ClusterJoinError(f"master returned an invalid response: {exc}") from exc


def join_master(master_url: str, token: str, node_id: str, self_url: str = "") -> dict:
    """Registers this node with a cluster master.

    Returns the master's response — `{"config": {...shareable subset...},
    "master_node_id": "..."}` — on success. Raises ClusterJoinError on any
    network failure or rejection (wrong token, master not actually a master).
    """
    url = master_url.rstrip("/") + "/api/cluster/join"
    return _post(url, token, {"node_id": node_id, "url": self_url or master_url})


def send_heartbeat(master_url: str, token: str, node_id: str, stats: dict | None = None) -> dict:
    """Pings the master to refresh this node's `last_seen`. Raises
    ClusterJoinError if the master doesn't recognize this node (it should
    re-join) or is unreachable."""
    url = master_url.rstrip("/") + "/api/cluster/heartbeat"
    return _post(url, token, {"node_id": node_id, "stats": stats or {}})


# ── deploy file templates ───────────────────────────────────────────────────
#
# Static file generation only — the dashboard never talks to the Docker or
# Kubernetes APIs itself (a deliberate scope decision: that would mean a new
# dependency, a mounted Docker socket or kubeconfig, and a much bigger attack
# surface for a "download my compose file" feature). These are just strings.

def render_docker_compose(slave_count: int = 2) -> str:
    slave_count = max(0, min(slave_count, 20))
    lines = [
        "# Generated by Synthelion — synthelion cluster deploy template.",
        "# Fill in SYNTHELION_NODE_TOKEN in a .env file or your secrets manager —",
        "# never commit the real value. Every service must use the SAME token.",
        "services:",
        "  synthelion-master:",
        "    image: synthelion:latest",
        "    environment:",
        "      - SYNTHELION_ROLE=master",
        "      - SYNTHELION_NODE_ID=master-1",
        "      - SYNTHELION_NODE_TOKEN=${SYNTHELION_NODE_TOKEN}",
        "    ports:",
        '      - "8787:8787"',
        "    volumes:",
        "      - synthelion-master-data:/home/synthelion/.synthelion",
        "    restart: unless-stopped",
        "",
    ]
    for i in range(1, slave_count + 1):
        lines += [
            f"  synthelion-node-{i}:",
            "    image: synthelion:latest",
            "    environment:",
            "      - SYNTHELION_ROLE=slave",
            f"      - SYNTHELION_NODE_ID=node-{i}",
            "      - SYNTHELION_NODE_TOKEN=${SYNTHELION_NODE_TOKEN}",
            "      - SYNTHELION_MASTER_URL=http://synthelion-master:8787",
            f"      - SYNTHELION_SELF_URL=http://synthelion-node-{i}:8787",
            "    depends_on:",
            "      - synthelion-master",
            "    volumes:",
            f"      - synthelion-node-{i}-data:/home/synthelion/.synthelion",
            "    restart: unless-stopped",
            "",
        ]
    lines.append("volumes:")
    lines.append("  synthelion-master-data:")
    for i in range(1, slave_count + 1):
        lines.append(f"  synthelion-node-{i}-data:")
    lines.append("")
    return "\n".join(lines)


def render_k8s_manifest(slave_count: int = 2) -> str:
    slave_count = max(0, min(slave_count, 20))
    return f"""\
# Generated by Synthelion — synthelion cluster deploy template.
# Fill in the real token in the Secret below (do not commit it) before applying.
apiVersion: v1
kind: Secret
metadata:
  name: synthelion-cluster-token
  namespace: synthelion
type: Opaque
stringData:
  token: "REPLACE_ME"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthelion-master
  namespace: synthelion
spec:
  replicas: 1
  selector:
    matchLabels: {{app: synthelion-master}}
  template:
    metadata:
      labels: {{app: synthelion-master}}
    spec:
      containers:
        - name: synthelion
          image: synthelion:latest
          ports: [{{containerPort: 8787}}]
          env:
            - name: SYNTHELION_ROLE
              value: "master"
            - name: SYNTHELION_NODE_ID
              value: "master-1"
            - name: SYNTHELION_NODE_TOKEN
              valueFrom: {{secretKeyRef: {{name: synthelion-cluster-token, key: token}}}}
---
apiVersion: v1
kind: Service
metadata:
  name: synthelion-master
  namespace: synthelion
spec:
  selector: {{app: synthelion-master}}
  ports: [{{port: 8787, targetPort: 8787}}]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthelion-node
  namespace: synthelion
spec:
  replicas: {slave_count}
  selector:
    matchLabels: {{app: synthelion-node}}
  template:
    metadata:
      labels: {{app: synthelion-node}}
    spec:
      containers:
        - name: synthelion
          image: synthelion:latest
          ports: [{{containerPort: 8787}}]
          env:
            - name: SYNTHELION_ROLE
              value: "slave"
            - name: SYNTHELION_MASTER_URL
              value: "http://synthelion-master:8787"
            - name: SYNTHELION_NODE_TOKEN
              valueFrom: {{secretKeyRef: {{name: synthelion-cluster-token, key: token}}}}
"""
