# Synthelion — Python port of Caveman (https://github.com/francescopaolopassaro/caveman)
# © 2026 Passaro Francesco Paolo — Digitalsolutions.it
from __future__ import annotations

import logging
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from typing import Callable

_log = logging.getLogger(__name__)

from synthelion.detector import LanguageDetector
from synthelion.models import CompressionLevel, CompressionResult
from synthelion.word_provider import FunctionWordProvider

_WORD_SPLIT = re.compile(
    r"[\w]+(?:'[\w]+)?|[^\w\s]", re.UNICODE
)

# Languages that capitalise all common nouns — the positional proper-noun
# heuristic is disabled for these (same as C# CapitalizedNounLanguages).
_CAPITALIZED_NOUN_LANGS = frozenset({"deu"})

# Language group → suffix lists (ported verbatim from C# IsDescriptiveWord)
_EN_ADV = ("ly", "wise", "wards")
_EN_ADJ = ("ous", "al", "ive", "able", "ible", "ful", "less", "ic", "ical", "ant", "ent", "ish", "like", "some")
_ROMANCE_ADV = ("mente",)
_ROMANCE_ADJ = ("oso", "osa", "ivo", "iva", "abile", "ibile", "ale", "are", "ese", "ista")
_GERMANIC_ADJ = ("lich", "ig", "isch", "sam", "bar", "haft", "los", "voll", "arm", "reich")
_SLAVIC_ADJ = ("ный", "ная", "ное", "ные", "ний", "ня", "нє", "ова", "еви", "ски", "цки", "скиј", "чки")


def _lang_group(iso3: str) -> str:
    return {
        "eng": "en",
        "ita": "romance", "fra": "romance", "spa": "romance", "por": "romance",
        "ron": "romance", "cat": "romance", "glg": "romance", "lat": "romance",
        "deu": "germanic", "nld": "germanic", "afr": "germanic",
        "swe": "germanic", "dan": "germanic", "nor": "germanic", "isl": "germanic",
        "rus": "slavic", "ukr": "slavic", "bel": "slavic", "bul": "slavic",
        "srp": "slavic", "hrv": "slavic", "slv": "slavic", "slk": "slavic",
        "ces": "slavic", "pol": "slavic", "mkd": "slavic",
        "ara": "semitic", "heb": "semitic", "fas": "semitic", "urd": "semitic",
        "hin": "indic", "ben": "indic", "mar": "indic", "tel": "indic",
        "tam": "indic", "kan": "indic",
        "zho": "east_asian", "jpn": "east_asian", "kor": "east_asian",
        "tha": "east_asian", "vie": "east_asian",
        "tur": "uralic_altaic", "kaz": "uralic_altaic", "fin": "uralic_altaic",
        "est": "uralic_altaic", "hun": "uralic_altaic", "hye": "uralic_altaic",
        "ell": "uralic_altaic",
    }.get(iso3.lower(), "other")


def _is_descriptive(word: str, group: str) -> bool:
    if len(word) < 4:
        return False
    w = word.lower()
    if group == "en":
        return any(w.endswith(s) and len(w) > len(s) + 1 for s in _EN_ADV) or \
               any(w.endswith(s) and len(w) > len(s) + 2 for s in _EN_ADJ)
    if group == "romance":
        if w.endswith("mente") and len(w) > 7:
            return True
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _ROMANCE_ADJ)
    if group == "germanic":
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _GERMANIC_ADJ)
    if group == "slavic":
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _SLAVIC_ADJ)
    if group == "semitic":
        return len(w) > 5 and (w.startswith("al") or w.startswith("el"))
    if group == "uralic_altaic":
        return any(w.endswith(s) for s in ("лар", "лер", "дар", "дер", "тар", "тер", "мен", "бен", "пен"))
    return False


def _is_number(token: str) -> bool:
    return all(c.isdigit() or c in ".,- " for c in token) and bool(token)


# Generic words are now loaded per-iso3 from {iso3}.generic.yaml.br files
# (generated by scripts/generate_worddata.py). No hardcoded word lists here.
_GENERIC_FALLBACK: frozenset[str] = frozenset({
    "time", "day", "year", "person", "thing", "place", "world", "life",
    "big", "small", "new", "old", "good", "bad",
    "now", "then", "today", "yesterday", "tomorrow", "always", "never",
})


@dataclass
class CompressionFilter:
    keep_only: set[str] | None = None  # categories: FUNC, PUNCT, NUM, PROPN, CONTENT
    remove: set[str] | None = None
    custom_predicate: Callable[[str], bool] | None = None


def _categorize(word: str, fw: frozenset[str]) -> str:
    if word.lower() in fw:
        return "FUNC"
    if _is_number(word):
        return "NUM"
    if word and word[0].isupper() and len(word) > 1:
        return "PROPN"
    return "CONTENT"


class CompressionService:
    """NLP prompt compressor: strips function words and lemmatizes tokens.

    Ported from C# CavemanCompressionService. Supports Light, Semantic and
    Aggressive compression levels across 50+ languages. Zero ML model dependency.
    """

    def __init__(
        self,
        word_provider: FunctionWordProvider | None = None,
        detector: LanguageDetector | None = None,
    ) -> None:
        self._provider = word_provider or FunctionWordProvider()
        self._detector = detector or LanguageDetector(self._provider)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def detect_language(self, text: str) -> str:
        return self._detector.detect(text)

    def detect_language_scores(self, text: str) -> dict[str, float]:
        return self._detector.detect_with_scores(text)

    def compress(
        self,
        text: str,
        level: CompressionLevel = CompressionLevel.SEMANTIC,
        iso3: str | None = None,
        custom_filter: CompressionFilter | None = None,
    ) -> CompressionResult:
        if not text or not text.strip():
            return CompressionResult(compressed_text="")
        try:
            lang = iso3 or self._detector.detect(text)
            return self.apply_compression(text, lang, level, custom_filter)
        except Exception as exc:
            _log.warning("compress() failed: %s", exc, exc_info=True)
            return CompressionResult(compressed_text=text, error_message=str(exc))

    def compress_batch(
        self,
        texts: list[str],
        level: CompressionLevel = CompressionLevel.SEMANTIC,
        max_workers: int = 4,
    ) -> list[CompressionResult]:
        """Compress a list of texts, using threads for batches larger than 8."""
        if len(texts) <= 8:
            return [self.compress(t, level) for t in texts]
        results: list[CompressionResult | None] = [None] * len(texts)
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futures = {ex.submit(self.compress, t, level): i for i, t in enumerate(texts)}
            for fut in as_completed(futures):
                results[futures[fut]] = fut.result()
        return results  # type: ignore[return-value]

    def apply_compression(
        self,
        text: str,
        iso3: str,
        level: CompressionLevel,
        custom_filter: CompressionFilter | None = None,
    ) -> CompressionResult:
        if not text or not text.strip():
            return CompressionResult(compressed_text="")

        fw = self._provider.get_function_words(iso3)
        lemmas = self._provider.get_lemma_map(iso3)
        proper_nouns = self._provider.get_proper_nouns(iso3)

        tokens = _tokenize(text)
        original_count = len(tokens)

        if level == CompressionLevel.NONE and custom_filter is None:
            return CompressionResult(
                compressed_text=text,
                original_tokens=original_count,
                compressed_tokens=original_count,
            )

        if custom_filter is not None:
            filtered = _apply_custom(tokens, fw, custom_filter)
        elif level == CompressionLevel.LIGHT:
            filtered = _filter_light(tokens, fw)
        elif level == CompressionLevel.SEMANTIC:
            filtered = _filter_semantic(tokens, fw, lemmas, proper_nouns, iso3)
        else:  # AGGRESSIVE
            generic = self._provider.get_generic_words(iso3) or _GENERIC_FALLBACK
            filtered = _filter_aggressive(tokens, fw, lemmas, proper_nouns, iso3, generic)

        compressed = " ".join(filtered)
        return CompressionResult(
            compressed_text=compressed,
            original_tokens=original_count,
            compressed_tokens=len(filtered),
        )


# ------------------------------------------------------------------
# Internal tokenization
# ------------------------------------------------------------------

class _Token:
    __slots__ = ("text", "is_punct")

    def __init__(self, text: str, is_punct: bool) -> None:
        self.text = text
        self.is_punct = is_punct


def _tokenize(text: str) -> list[_Token]:
    tokens = []
    for m in _WORD_SPLIT.finditer(text):
        t = m.group()
        is_punct = not (t[0].isalpha() or t[0].isdigit())
        tokens.append(_Token(t, is_punct))
    return tokens


# ------------------------------------------------------------------
# Proper-noun detection
# ------------------------------------------------------------------

def _detect_proper_nouns(
    tokens: list[_Token],
    iso3: str,
    proper_nouns: frozenset[str],
) -> list[bool]:
    cap_noun_lang = iso3.lower() in _CAPITALIZED_NOUN_LANGS
    has_gazetteer = bool(proper_nouns)
    result = [False] * len(tokens)
    sentence_start = True

    for i, tok in enumerate(tokens):
        if tok.is_punct:
            if tok.text in (".", "!", "?", "…"):
                sentence_start = True
            continue
        if tok.text and tok.text[0].isupper():
            in_gazetteer = has_gazetteer and tok.text.lower() in proper_nouns
            if cap_noun_lang:
                result[i] = in_gazetteer
            else:
                result[i] = (not sentence_start) or in_gazetteer
        sentence_start = False

    return result


# ------------------------------------------------------------------
# Compression filters
# ------------------------------------------------------------------

def _filter_light(tokens: list[_Token], fw: frozenset[str]) -> list[str]:
    return [
        t.text for t in tokens
        if not t.is_punct and t.text.lower() not in fw
    ]


def _lemma_or_lower(text: str, lemmas: dict[str, str]) -> str:
    lower = text.lower()
    return lemmas.get(lower, lower)


def _filter_semantic(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
) -> list[str]:
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    out = []
    for i, tok in enumerate(tokens):
        if tok.is_punct:
            continue
        if is_proper[i]:
            out.append(tok.text)
            continue
        if _is_number(tok.text):
            continue
        if tok.text.lower() in fw:
            continue
        normalized = _lemma_or_lower(tok.text, lemmas)
        if normalized in fw:
            continue
        out.append(normalized)
    return out


def _filter_aggressive(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
    generic: frozenset[str],
) -> list[str]:
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    out = []
    for i, tok in enumerate(tokens):
        if tok.is_punct:
            continue
        if is_proper[i]:
            out.append(tok.text)
            continue
        if len(tok.text) <= 1 and not tok.text[0:1].isalpha():
            continue
        if _is_number(tok.text):
            continue
        lower = tok.text.lower()
        if lower in fw:
            continue
        normalized = _lemma_or_lower(tok.text, lemmas)
        if len(normalized) <= 1:
            continue
        if normalized in fw or normalized in generic:
            continue
        if _is_descriptive(normalized, group):
            continue
        out.append(normalized)
    return out


def _apply_custom(
    tokens: list[_Token],
    fw: frozenset[str],
    f: CompressionFilter,
) -> list[str]:
    out = []
    for tok in tokens:
        if tok.is_punct and f.remove and "PUNCT" in f.remove:
            continue
        if f.keep_only is not None:
            cat = _categorize(tok.text, fw)
            if cat not in f.keep_only:
                continue
        elif f.remove and "FUNC" in f.remove:
            if tok.text.lower() in fw:
                continue
        if f.custom_predicate is not None and not f.custom_predicate(tok.text):
            continue
        out.append(tok.text)
    return out
