# Synthelion — Python port of Caveman (https://github.com/francescopaolopassaro/caveman)
# © 2026 Passaro Francesco Paolo — Digitalsolutions.it
from __future__ import annotations

import importlib.resources
import threading
from functools import lru_cache

import brotli

from synthelion.models import WordDataFile

# Languages with hand-curated .excl.yaml.br and .generic.yaml.br supplementary files.
# All function words now live in the YAML worddata files — no inline lists.
_CURATED_ISO3S: frozenset[str] = frozenset({
    "eng", "ita", "fra", "deu", "spa", "por", "nld",
})


class FunctionWordProvider:
    """Loads per-language function words, lemmas and proper nouns from embedded worddata.

    Ported from C# FunctionWordProvider. Language data files are brotli-compressed
    YAML blobs shipped with the package (synthelion/worddata/*.yaml.br + _index.br).

    Supplementary files generated by scripts/generate_worddata.py:
      {iso3}.excl.yaml.br   — exclusive markers for disambiguation
      {iso3}.generic.yaml.br — generic words for aggressive compression
    """

    @classmethod
    def get_curated_iso3s(cls) -> frozenset[str]:
        """Return ISO 639-3 codes that have supplementary .excl and .generic files."""
        return _CURATED_ISO3S

    _index_lock = threading.Lock()
    _index: dict[str, tuple[str, str, frozenset[str]]] | None = None
    _fw_cache: dict[str, frozenset[str]] = {}
    _lemma_cache: dict[str, dict[str, str]] = {}
    _word_data_cache: dict[str, WordDataFile | None] = {}
    _excl_cache: dict[str, tuple[frozenset[str], frozenset[str]]] = {}
    _generic_cache: dict[str, frozenset[str]] = {}

    @classmethod
    def _worddata_path(cls) -> importlib.resources.abc.Traversable:
        return importlib.resources.files("synthelion.worddata")

    @classmethod
    def _load_index(cls) -> dict[str, tuple[str, str, frozenset[str]]]:
        if cls._index is not None:
            return cls._index
        with cls._index_lock:
            if cls._index is not None:
                return cls._index
            idx: dict[str, tuple[str, str, frozenset[str]]] = {}
            try:
                data = cls._worddata_path().joinpath("_index.br").read_bytes()
                raw = brotli.decompress(data)
                for line in raw.decode("utf-8").splitlines():
                    if not line:
                        continue
                    parts = line.split("\t")
                    if len(parts) < 3:
                        continue
                    iso3, iso1, name = parts[0], parts[1], parts[2]
                    fw = frozenset(p for p in parts[3:] if p)
                    idx[iso3] = (iso1, name, fw)
            except Exception:
                pass
            cls._index = idx
        return cls._index

    # ------------------------------------------------------------------
    # Function words
    # Curated languages load from {iso3}.fw.yaml.br (precise grammatical
    # function words — articles, pronouns, prepositions, conjunctions,
    # auxiliaries).  All other languages load from _index.br.
    # ------------------------------------------------------------------

    def get_function_words(self, iso3: str) -> frozenset[str]:
        iso3 = iso3.lower()
        cached = FunctionWordProvider._fw_cache.get(iso3)
        if cached is not None:
            return cached

        # Curated languages: load from .fw.yaml.br (hand-curated grammatical FW)
        if iso3 in _CURATED_ISO3S:
            words: list[str] = []
            try:
                data = self._worddata_path().joinpath(f"{iso3}.fw.yaml.br").read_bytes()
                raw = brotli.decompress(data).decode("utf-8")
                in_section = False
                for line in raw.splitlines():
                    stripped = line.rstrip()
                    if not stripped:
                        continue
                    if not stripped[0].isspace():
                        in_section = stripped.rstrip(":") == "function_words"
                        continue
                    if in_section:
                        t = stripped.strip()
                        if t.startswith("- "):
                            w = t[2:].strip()
                            if w:
                                words.append(w)
            except Exception:
                pass
            result = frozenset(words)
        else:
            idx = self._load_index()
            entry = idx.get(iso3)
            result = entry[2] if entry else frozenset()

        FunctionWordProvider._fw_cache[iso3] = result
        return result

    def get_all_supported_iso3(self) -> set[str]:
        supported = set(self._load_index().keys())
        supported.update(_CURATED_ISO3S)
        return supported

    def is_function_word(self, word: str, iso3: str) -> bool:
        return word.strip().lower() in self.get_function_words(iso3)

    # ------------------------------------------------------------------
    # Supplementary: exclusive markers & ambiguous words
    # ------------------------------------------------------------------

    def _load_excl(self, iso3: str) -> tuple[frozenset[str], frozenset[str]]:
        """Load {iso3}.excl.yaml.br → (exclusive_markers, ambiguous_with)."""
        iso3 = iso3.lower()
        cached = FunctionWordProvider._excl_cache.get(iso3)
        if cached is not None:
            return cached
        excl: list[str] = []
        amb: list[str] = []
        try:
            data = self._worddata_path().joinpath(f"{iso3}.excl.yaml.br").read_bytes()
            raw = brotli.decompress(data).decode("utf-8")
            section = None
            for line in raw.splitlines():
                stripped = line.rstrip()
                if not stripped:
                    continue
                if not stripped[0].isspace():
                    key = stripped.rstrip(":")
                    section = key if key in ("exclusive_markers", "ambiguous_with") else None
                    continue
                t = stripped.strip()
                if t.startswith("- "):
                    w = t[2:].strip()
                    if section == "exclusive_markers":
                        excl.append(w)
                    elif section == "ambiguous_with":
                        amb.append(w)
        except Exception:
            pass
        result = (frozenset(excl), frozenset(amb))
        FunctionWordProvider._excl_cache[iso3] = result
        return result

    def get_exclusive_markers(self, iso3: str) -> frozenset[str]:
        """Words unique to this language — used by detector for disambiguation."""
        return self._load_excl(iso3)[0]

    def get_ambiguous_words(self, iso3: str) -> frozenset[str]:
        """Words shared with other curated languages — down-weighted in detection."""
        return self._load_excl(iso3)[1]

    # ------------------------------------------------------------------
    # Supplementary: generic compression words (aggressive mode)
    # ------------------------------------------------------------------

    def get_generic_words(self, iso3: str) -> frozenset[str]:
        """Load {iso3}.generic.yaml.br — generic words removed in aggressive mode."""
        iso3 = iso3.lower()
        cached = FunctionWordProvider._generic_cache.get(iso3)
        if cached is not None:
            return cached
        words: list[str] = []
        try:
            data = self._worddata_path().joinpath(f"{iso3}.generic.yaml.br").read_bytes()
            raw = brotli.decompress(data).decode("utf-8")
            in_section = False
            for line in raw.splitlines():
                stripped = line.rstrip()
                if not stripped:
                    continue
                if not stripped[0].isspace():
                    in_section = stripped.rstrip(":") == "generic_words"
                    continue
                if in_section:
                    t = stripped.strip()
                    if t.startswith("- "):
                        w = t[2:].strip()
                        if w:
                            words.append(w)
        except Exception:
            pass
        result = frozenset(words)
        FunctionWordProvider._generic_cache[iso3] = result
        return result

    # ------------------------------------------------------------------
    # Full word data (lemmas, verbs, proper nouns)
    # ------------------------------------------------------------------

    def load_word_data(self, iso3: str) -> WordDataFile | None:
        iso3 = iso3.lower()
        if iso3 in FunctionWordProvider._word_data_cache:
            return FunctionWordProvider._word_data_cache[iso3]
        try:
            data = self._worddata_path().joinpath(f"{iso3}.yaml.br").read_bytes()
            raw = brotli.decompress(data)
            result = _parse_yaml(raw.decode("utf-8"))
        except Exception:
            result = None
        FunctionWordProvider._word_data_cache[iso3] = result
        return result

    def get_lemma_map(self, iso3: str) -> dict[str, str]:
        iso3 = iso3.lower()
        if iso3 in FunctionWordProvider._lemma_cache:
            return FunctionWordProvider._lemma_cache[iso3]
        data = self.load_word_data(iso3)
        if data is None:
            FunctionWordProvider._lemma_cache[iso3] = {}
            return {}
        m: dict[str, str] = {}
        for lemma, forms in data.verbs.items():
            if not lemma:
                continue
            for f in forms:
                if f:
                    m[f.lower()] = lemma
        for form, lemma in data.lemmas.items():
            if form and lemma:
                m[form.lower()] = lemma
        FunctionWordProvider._lemma_cache[iso3] = m
        return m

    def get_proper_nouns(self, iso3: str) -> frozenset[str]:
        data = self.load_word_data(iso3)
        if data is None or not data.proper_nouns:
            return frozenset()
        return frozenset(n.lower() for n in data.proper_nouns if n)


# ---------------------------------------------------------------------------
# Streaming YAML parser — ported from C# FunctionWordProvider.ParseYaml
# ---------------------------------------------------------------------------
def _strip_quotes(s: str) -> str:
    if len(s) >= 2:
        if s[0] == '"' and s[-1] == '"':
            return s[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        if s[0] == "'" and s[-1] == "'":
            return s[1:-1].replace("''", "'")
    return s


def _try_parse_kv(t: str) -> tuple[str, str] | None:
    if not t:
        return None
    if t[0] == '"':
        close = _closing_quote(t, 0)
        if close < 0:
            return None
        colon = t.find(":", close + 1)
        if colon < 0:
            return None
        key = _strip_quotes(t[: close + 1])
    else:
        colon = t.find(":")
        if colon < 0:
            return None
        key = _strip_quotes(t[:colon].strip())
    value = _strip_quotes(t[colon + 1 :].strip())
    return key, value


def _closing_quote(s: str, open_idx: int) -> int:
    i = open_idx + 1
    while i < len(s):
        if s[i] == "\\":
            i += 2
            continue
        if s[i] == '"':
            return i
        i += 1
    return -1


_SEC_NONE = 0
_SEC_FW = 1
_SEC_LEMMAS = 2
_SEC_VERBS = 3
_SEC_PROPER = 4


def _parse_yaml(text: str) -> WordDataFile:
    data = WordDataFile()
    section = _SEC_NONE
    current_verb: str | None = None

    for line in text.splitlines():
        if not line:
            continue
        if not line[0].isspace():
            key = line.rstrip()
            if key.startswith("iso3:"):
                data.iso3 = key[5:].strip()
                section = _SEC_NONE
            elif key.startswith("iso1:"):
                data.iso1 = key[5:].strip()
                section = _SEC_NONE
            elif key.startswith("name:"):
                data.name = key[5:].strip()
                section = _SEC_NONE
            elif key == "function_words:":
                section = _SEC_FW
            elif key == "lemmas:":
                section = _SEC_LEMMAS
            elif key == "verbs:":
                section = _SEC_VERBS
                current_verb = None
            elif key == "proper_nouns:":
                section = _SEC_PROPER
            else:
                section = _SEC_NONE
            continue

        t = line.strip()
        if section == _SEC_FW:
            if t and t[0] == "-":
                w = _strip_quotes(t[1:].strip())
                if w:
                    data.function_words.append(w)
        elif section == _SEC_LEMMAS:
            kv = _try_parse_kv(t)
            if kv and kv[0] and kv[1]:
                data.lemmas[kv[0]] = kv[1]
        elif section == _SEC_VERBS:
            if t and t[0] == "-":
                if current_verb is not None:
                    f = _strip_quotes(t[1:].strip())
                    if f:
                        data.verbs.setdefault(current_verb, []).append(f)
            else:
                kv = _try_parse_kv(t)
                if kv and kv[0]:
                    current_verb = kv[0]
                    if current_verb not in data.verbs:
                        data.verbs[current_verb] = []
        elif section == _SEC_PROPER:
            if t and t[0] == "-":
                n = _strip_quotes(t[1:].strip())
                if n:
                    data.proper_nouns.append(n)

    return data
